fix: scroll to top on click event
vaadin/vaadin-router pull request #547
Opened 2021-01-29 12:28 UTC by haijian-vaadin

Apply @abdonrd 's [patch](https://github.com/IBM/pwa-lit-template/blob/main/patches/@vaadin+router+1.7.2.patch) to https://github.com/vaadin/vaadin-router/issues/43. 
Not optimal, but maybe a good first step.

2021-01-29 12:59 UTC, platosha requested changes
Please add a test for this.

2021-01-29 12:59 UTC, platosha commented on src/triggers/click.js
> +    window.scrollTo(0, 0);
Maybe we need to move that inside the `if` statement below: only scroll if the link click is handled in the router, i. e., is not outside the router’s base URL.

2021-01-29 13:58 UTC, platosha approved these changes

2021-02-04 08:54 UTC, merged

2021-02-04 09:15 UTC, abdonrd commented
@haijian-vaadin Thanks! Is there an estimate for the next release?

2021-02-04 13:18 UTC, haijian-vaadin commented
> @haijian-vaadin Thanks! Is there an estimate for the next release?

Hi @abdonrd, I will try to cherry-pick this fix to 1.x and make a release next Friday (12.2.2012), maybe also make a 2.0 release as well. 
And thanks a lot for your contributions to `vaadin-rouer` 🙇‍♂️.